#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 14 10:37:47 2019

@author: albertlu
"""
lis = []
def isPrime(n):
    if n<2:
        return False
    for i in range(2, int(n**0.5) +1):
        if n%i==0:
            return False
    return True
for i in range(0, 1000000):
    if isPrime(i):
        lis.append(i)
print(lis)
finalList = []
for num in lis:
    trunk = True
    dorito = str(num)
    for i in range(-len(dorito), 0):
        if not isPrime(int(dorito[i:])):
            trunk = False
            break
    if trunk:
        for i in range(1, len(dorito)):
            if not isPrime(int(dorito[:i])):
                trunk = False
                break
    if trunk:
        finalList.append(num)
total = 0
print(finalList)
for num in finalList:
    total += num
total -= 17
print(total)
        