#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 30 14:23:40 2019

@author: albertlu
"""
dorito = True
for i in range(1, 200000000, 1):
    dorito = True
    for j in range(1,20,1):
        if(i%j!=0):
            dorito = False
            break
    if dorito:
        print(i)
        break