#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul  7 20:03:15 2019

@author: albertlu
"""
total = 0

for ones in range(0, 101):
    for twos in range(0, 51):
        for fives in range(0, 21):
            for tens in range(0, 11):
                for twens in range(0, 6):
                    if 1*ones + 2*twos + 5*fives + 10*tens + 20*twens == 100:
                        total +=1
print(total)