#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 17 20:36:00 2019

@author: albertlu
"""



close = 10        
index1 = 0
index2 = 0
for i in range(0, 2828):
    for j in range(0, 2828):
        if abs(8000000 - (i)*(i-1)*(j)*(j-1))<close:
            close = 8000000 - (i)*(i-1)*(j)*(j-1)
            index1 = i
            index2 = j
print(index1)
print(index2)
print(close)
        