#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 28 21:23:57 2019

@author: albertlu
"""
total = 0

for i in range(0, 1000):
    if i%3==0 or i%5==0:
        total += i
print(total)
