#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 19 14:46:54 2019

@author: albertlu
"""

arr = []
finalArr = []
finalArr2 = []
for i in range(1, 5000):
    arr.append(i*(3*i-1)/2)
print(len(arr))
for i in range(0, len(arr)-1):
    print(i)
    for j in range(i, len(arr)):       
        if int((1+(1+24*arr[i] + 24*arr[j])**0.5)/6) ==  (1+(1+24*arr[i] + 24*arr[j])**0.5)/6 and int((1+(1+24*arr[j] - 24*arr[i])**0.5)/6) ==  (1+(1+24*arr[j] - 24*arr[i])**0.5)/6:
           finalArr.append(arr[i])
           finalArr2.append(arr[j])
print(finalArr)
print(finalArr2)
print(finalArr2[0]-finalArr[0])
           