#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  4 17:52:48 2019

@author: albertlu
"""

import math
lis = [0,0,0,0,0,0,0,0,0,0]
j = 9
i = 999999

while(i>0):
    if(math.factorial(j)<=i):
        i -= math.factorial(j)
        lis[j] += 1
    else:
        j -=1
lists = [0,1,2,3,4,5,6,7,8,9]
complete = ""
for i in range(9, -1, -1):
    print(lists[lis[i]])
    complete += str((lists[lis[i]]))
    lists.pop(lis[i])
print(complete)
print(lis)