#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  4 19:49:19 2019

@author: albertlu
"""

for i in range(0, 400, 1):
    for j in range(0, 400, 1):
        if(i**2+j**2 == (1000-i-j)**2):
            print(i)
            print(j)
            break