#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul  5 11:13:39 2019

@author: albertlu
"""
lis = []
for i in range(2, 101, 1):
    for j in range(2, 101, 1):
        if(i**j not in lis):
            lis.append(i**j)
print(len(lis))
        