#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 28 21:27:47 2019

@author: albertlu
"""
total = 0
checker = 0
a = 1 
b = 1
i = 0
while i<4000000:
    i = a+b
    a = b
    b = i
    if checker%3 == 0:
        total += i
    checker += 1
print(total)
        
    