#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 28 21:39:51 2019

@author: albertlu
"""
import math
lis = []
total = 0
dorito = True
for i in range(3, 1000000):
    rent = 0
    for j in range(0, len(str(i))):
        rent += math.factorial(int(str(i)[j]))
    if rent == i:
        total += i
        lis.append(i)
print(lis)
print(total)
        
    