#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 30 15:44:30 2019

@author: albertlu
"""
total = 0
total2 = 0
for i in range(1, 101, 1):
    total += i**2
for i in range(1, 101, 1):
    total2 += i
total3 = total-total2**2
print(total3)
print(total)
print(total2)
