#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 17 21:02:06 2019

@author: albertlu
"""
abundants = []
for i in range(1, 28123):
    total = 0
    for j in range(1, int(i/2)+1):
        if i%j == 0:
            total +=j
    if total>i:
        abundants.append(i)
print(abundants)
print(len(abundants))
sumAbuns = []
total = 0
totalList = []
for i in range(0, 28123):
    totalList.append(True)
for i in range(0, len(abundants)):
    print(i)
    for j in range(i, len(abundants)):
        if abundants[i]+abundants[j]<len(totalList):
            totalList[abundants[i]+abundants[j]] = False
for i in range(0, len(totalList)):
    if totalList[i]:
        total+= i
print(total)
    
    
