#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 14 10:20:54 2019

@author: albertlu
"""
lis = []
lis2 = []
def convert(n):
    started = False
    k = 19
    conversion = ""
    while k>-1:
        if 2**k>n:
            if started:
                conversion += "0"
        else:
            n -= 2**k
            started = True
            conversion += "1"
        k-=1
    return conversion

print(convert(5))

for i in range(0, 1000000):
    if str(i) == str(i)[::-1] and convert(i) == convert(i)[::-1]:
        lis.append(i)
        lis2.append(convert(i))
total = 0
for num in lis:
    total += num
print(total)
print(lis)
print(lis2)
    